apiVersion: apps/v1
kind: Deployment
metadata:
  name: bugbase-issue-deployment
  labels:
    app: bugbase-issue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bugbase-issue
  template:
    metadata:
      labels:
        app: bugbase-issue
    spec:
      containers:
        - name: bugbase-issue
          image: bugbase-issue
          resources:
            limits:
              memory: 128Mi
              cpu: 500m
          ports:
            - containerPort: 8080
              name: server
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 20
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            initialDelaySeconds: 20
            periodSeconds: 5
          env:
            - name: PORT_APP_ISSUE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PORT_APP_ISSUE
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_PORT
            - name: DB_SSL_MODE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_SSL_MODE
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_DB
          # TODO: Currently only for local testing. Remove for production deployment.
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: bugbase-issue-service
spec:
  type: ClusterIP
  selector:
    app: bugbase-issue
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
