apiVersion: apps/v1
kind: Deployment
metadata:
  name: bugbase-issue-deployment
  labels:
    app: bugbase-issue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bugbase-issue
  template:
    metadata:
      labels:
        app: bugbase-issue
    spec:
      containers:
        - name: bugbase-issue
          image: bugbase-issue
          resources:
            limits:
              memory: 128Mi
              cpu: 500m
          ports:
            # TODO: KeyValue store
            - containerPort: 8080
              name: server
          ## TODO: healthcheck
          #livenessProbe:
          #  httpGet:
          #    path: /health/live
          #    port: server
          #  initialDelaySeconds: 20
          #  periodSeconds: 5
          ## TODO: healthcheck
          #readinessProbe:
          #  httpGet:
          #    path: /health/ready
          #    port: server
          #  initialDelaySeconds: 20
          #  periodSeconds: 5
          # TODO: KeyValue store
          env:
            - name: APP_PORT
              value: "8080"
            - name: DB_HOST
              value: "bugbase-database-service.default.svc"
          # TODO: Currently only for local testing. Remove for production deployment.
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: bugbase-issue-service
spec:
  type: ClusterIP
  selector:
    app: bugbase-issue
  ports:
    # TODO: KeyValue store
    - port: 8080
      protocol: TCP
      targetPort: server
