apiVersion: v1
kind: ConfigMap
metadata:
  name: bugbase-configmap
data:
  PORT_APP_ISSUE: "8080"
  PORT_APP_STATIC: "8081"
  PORT_APP_BULK: "8082"
  PORT_APP_INGRESS: "8083"

  URL_PREFIX_ISSUE: "/issue"
  URL_PREFIX_STATIC: ""
  URL_PREFIX_BULK: "/bulk"
  URL_PREFIX_INGRESS: "/ingress"

  DB_NAME: "bugbase"
  DB_USER: "bugbase"
  DB_HOST: "bugbase-database-service.default.svc"
  DB_PORT: "5432"
  DB_SSL_MODE: "disable"
