apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  PORT_APP_ISSUE: "8080"
  PORT_APP_STATIC: "8081"

  URL_PREFIX_ISSUE: "http://localhost:8080"
  URL_PREFIX_STATIC: "http://localhost:8081"

  DB_HOST: "localhost"
  DB_PORT: "5432"
  DB_SSL_MODE: "disable"
