apiVersion: v1
kind: PersistentVolume
metadata:
  name: bugbase-database
  labels:
    app: bugbase-database
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  hostPath:
    path: /data/postgresql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bugbase-database
  labels:
    app: bugbase-database
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 50Mi
  accessModes:
    - ReadWriteMany
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bugbase-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bugbase-database
  template:
    metadata:
      labels:
        app: bugbase-database
    spec:
      containers:
        - name: postgres
          image: postgres
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            # TODO: KeyValue store
            - containerPort: 5432
              name: dbport
          env:
            # TODO: KeyValue store
            - name: POSTGRES_DB
              value: bugbase
            # TODO: KeyValue store
            - name: POSTGRES_USER
              value: bugbase
            # TODO: Secrets
            - name: POSTGRES_PASSWORD
              value: password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
          imagePullPolicy: IfNotPresent
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: bugbase-database
---
apiVersion: v1
kind: Service
metadata:
  name: bugbase-database
spec:
  type: NodePort
  selector:
    app: bugbase-database
  ports:
  - port: 5432
    targetPort: dbport
