apiVersion: v1
kind: PersistentVolume
metadata:
  name: bugbase-database-pv
  labels:
    app: bugbase-database
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  hostPath:
    path: /data/postgresql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bugbase-database-pvc
  labels:
    app: bugbase-database
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 50Mi
  accessModes:
    - ReadWriteMany
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bugbase-database-deployment
  labels:
    app: bugbase-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bugbase-database
  template:
    metadata:
      labels:
        app: bugbase-database
    spec:
      containers:
        - name: bugbase-database
          image: ghcr.io/rsopms/bugbase-database
          ports:
            - containerPort: 5432
              name: dbport
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: bugbase-database-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: bugbase-database-service
spec:
  type: ClusterIP
  selector:
    app: bugbase-database
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
