apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  POSTGRES_PASSWORD: cGFzc3dvcmQ= # base64-encoded "password"
  POSTGRES_USER: YnVnYmFzZQ==     # base64-encoded "bugbase"
  POSTGRES_DB: YnVnYmFzZQ==       # base64-encoded "bugbase"
