name: (app-login) Vet and test GO code

on:
  push:
    paths:
      - 'app-login/**'

jobs:
  lint:
    name: Vet and test GO code
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./app-login
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup GO
        uses: actions/setup-go@v5
        with:
          go-version-file: app-login/go.mod
      - name: Tidy Go mod
        run: go mod tidy && git diff --exit-code
      - name: Download Go modules
        run: go mod download
      - name: Verify Go modules
        run: go mod verify
      - name: Vet GO code
        run: go vet ./...
      - name: Format Go code
        run: gofmt -l -s -w . && git diff --exit-code
      - name: Test GO code
        run: go test ./...
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -f ./app-login/Dockerfile --tag ghcr.io/rsopms/bugbase-login:${{ github.run_id }} .
      - name: Log into GHCR
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push Docker image to GHCR
        run: docker push ghcr.io/rsopms/bugbase-login:${{ github.run_id }}
