name: (framework) Vet and test GO code

on:
  push:
    paths:
      - framework/**

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup GO
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - name: Vet GO code
        working-directory: ./framework
        run: |
          go vet ./...
      - name: Test GO code
        working-directory: ./framework
        run: |
          go test ./...
